title: Hidayah Bashir Dayyib
description: "Portfolio of Hidayah Bashir Dayyib, Data Analyst and Content Creator"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_username
github_username: your_github_username

#Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

  # Author
author:
  name: "Hidayah Bashir Dayyib"
  email: "your-email@example.com"
  twitter: your_twitter_username
  github: your_github_username
  linkedin: your_linkedin_profile
  description: "Data Analyst, Content Creator, and Instructor"

  # Permalinks
permalink: /:categories/:title/

# Google Analytics (optional)
google_analytics: UA-XXXXXXXX-X


#Exclude from processing
exclude:
  -Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  

